version: "3"

services:
  nginx:
    image: nginx:1.15.11-alpine
    working_dir: /data/www
    expose:
      - "80"
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - backend
    volumes:
      - code:/data/www
      - nginx-conf:/etc/nginx/conf.d
    command:
      - /bin/sh
      - -c
      - |
        sed -i 's/#gzip  on.*/gzip  on;/g' /etc/nginx/nginx.conf
        sed -i '/gzip  on.*/a\    gzip_comp_level 6;' /etc/nginx/nginx.conf
        sed -i '/gzip_comp_level.*/a\    gzip_http_version 1.1;' /etc/nginx/nginx.conf
        sed -i '/gzip_comp_level.*/a\    gzip_types text/plain text/css application/json application/x-javascript text/xml application/xml application/xml+rss text/javascript;' /etc/nginx/nginx.conf
        sed -i 's/{{ WEB }}/web/g' /etc/nginx/conf.d/nginx_cert.conf
        nginx -g 'daemon off;'
  web:
    image: gaeamobile/certmanger:latest
    environment:
      - DB_NAME=ssl_cert              # 数据库名称, 默认: ssl_cert
      - DB_USER=root                  # 数据库账号, 默认: root
      - DB_PASSWORD=root123456        # 数据库密码, 默认: root123456
      - DB_HOST=127.0.0.1             # 数据库地址, 默认: 127.0.0.1
      - DB_PORT=3306                  # 数据库端口, 默认: 3306
      - ADMINS_EMAIL=admin@admin.com  # 管理员邮箱, admin账号对应的邮箱, 默认admin@admin.com
      - EMAIL_HOST=                   # 发送邮件的服务器地址
      - EMAIL_HOST_USER=              # 发送邮件的邮箱
      - EMAIL_PASSWORD=               # 发送邮件的邮箱密码
      - EMAIL_PORT=                   # 发送邮件的邮箱服务器端口号
      - EMAIL_SSL=True                # 发送邮件的邮箱是否开启加密, True|False (默认为True)
      - STAGING=False                 # 是否使用测试模式创建证书, True: 测试模式, False: 关闭测试模式（用于正式环境）。注: 测试模式下创建的证书不能使用，此模式只适用于代码测试
    volumes:
      - code:/data/www
      - nginx-conf:/etc/nginx/conf.d
    expose:
      - "8000"
    networks:
      - backend
    command:
      - /bin/sh
      - -c
      - |
        /data/www/scripts/run.sh
networks:
  backend:
volumes:
  code:
  nginx-conf:

