# Generated by Django 2.1 on 2019-09-06 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='域名')),
                ('extensive_domain', models.BooleanField(verbose_name='泛域名')),
                ('status', models.CharField(choices=[('valid', '有效'), ('invalid', '无效'), ('pending', '创建中'), ('failed', '失败')], default='valid', max_length=20, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='开始日期')),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2019, 12, 5, 10, 52, 21, 999709), verbose_name='过期日期')),
                ('dns', models.CharField(choices=[('dnspod', 'dnspod'), ('cloudflare', 'cloudflare'), ('aliyun', 'aliyun')], max_length=20, verbose_name='DNS解析商')),
                ('dns_account', models.CharField(max_length=150, verbose_name='DNS API账号')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SSLCertContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_content', models.TextField(verbose_name='证书')),
                ('key_content', models.TextField(verbose_name='key')),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ssl_cert.Domain')),
            ],
            options={
                'verbose_name': '证书内容',
                'verbose_name_plural': '证书内容',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='SubDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], max_length=5, verbose_name='协议')),
                ('sub_domain', models.CharField(db_index=True, max_length=253, verbose_name='子域名')),
                ('record_type', models.CharField(choices=[('A', 'A'), ('CNAME', 'CNAME'), ('AAAA', 'AAAA'), ('MX', 'MX'), ('NS', 'NS'), ('SRV', 'SRV'), ('CAA', 'CAA'), ('explicit_URL', 'explicit_URL'), ('implicit_URL', 'implicit_URL')], max_length=20, verbose_name='记录类型')),
                ('record_value', models.CharField(max_length=198, verbose_name='记录值')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始日期')),
                ('expire_date', models.DateTimeField(blank=True, null=True, verbose_name='过期日期')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_cert.Domain', verbose_name='主域名')),
            ],
            options={
                'verbose_name': '子域名',
                'verbose_name_plural': '子域名',
            },
        ),
        migrations.CreateModel(
            name='SubSyncLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='用户名')),
                ('sync_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='同步时间')),
            ],
            options={
                'verbose_name': '子域名同步频率限制',
                'verbose_name_plural': '子域名同步频率限制',
            },
        ),
        migrations.CreateModel(
            name='ToEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ssl_cert.Domain')),
            ],
            options={
                'verbose_name': '通知邮箱',
                'verbose_name_plural': '通知邮箱',
                'ordering': ('-id',),
            },
        ),
    ]
