# Generated by Django 2.1.12 on 2019-09-08 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdomains',
            name='comment',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 7, 21, 52, 30, 731409), verbose_name='过期日期'),
        ),
    ]
