# Generated by Django 2.1.12 on 2019-09-09 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_cert', '0002_auto_20190908_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsynclimit',
            name='domain',
            field=models.CharField(default=1, max_length=100, verbose_name='域名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='domain',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 8, 9, 47, 3, 330339), verbose_name='过期日期'),
        ),
    ]
